# Generated by Django 3.2.11 on 2022-03-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                ("model", models.CharField(max_length=255)),
                (
                    "fields",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "where",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
