# Generated by Django 3.2.11 on 2022-02-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('model', models.CharField(choices=[], max_length=255)),
                ('fields', models.JSONField(blank=True)),
                ('order', models.JSONField(blank=True)),
                ('where', models.JSONField(blank=True)),
            ],
        ),
    ]
