# Generated by Django 3.2.11 on 2022-03-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerozero", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryreport",
            name="fields",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queryreport",
            name="order",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queryreport",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="queryreport",
            name="where",
            field=models.TextField(blank=True, null=True),
        ),
    ]
