# Generated by Django 3.2.11 on 2022-04-14 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerozero', '0002_auto_20220309_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryreport',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QueryReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('success', models.BooleanField(null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', related_query_name='logs', to='zerozero.queryreport')),
            ],
        ),
    ]
