# Generated by Django 3.2.11 on 2022-04-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerozero', '0003_auto_20220414_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryreport',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queryreport',
            name='order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queryreport',
            name='where',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
