# Generated by Django 3.2.11 on 2022-04-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerozero', '0004_json_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryreport',
            name='interval',
            field=models.IntegerField(blank=True, choices=[(None, 'Never'), (60, '1 Hour'), (240, '4 Hours'), (720, '12 Hours'), (1440, '1 Day'), (10080, '1 Week')], null=True),
        ),
    ]
