# Generated by Django 3.2.11 on 2022-04-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerozero', '0005_alter_queryreport_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryreport',
            name='fields',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='queryreport',
            name='order',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='queryreport',
            name='where',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
