# Generated by Django 3.2.11 on 2022-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerozero', '0006_auto_20220419_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryreport',
            name='fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='queryreport',
            name='order',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='queryreport',
            name='where',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
