# Generated by Django 3.2.10 on 2022-01-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0004_add_excluded_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exampleschild",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                related_query_name="children",
                to="test_app.example",
            ),
        ),
    ]
