# Generated by Django 3.2.11 on 2022-04-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_examplebetter'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplebetter',
            name='json_blob',
            field=models.JSONField(null=True),
        ),
    ]
